name: Metrics
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate and commit metrics
        uses: IzonIcy/metrics-generator/action.yml@main
        with:
          target_repository: IzonIcy/IzonIcy
          target_branch: main
          access_token: ${{ secrets.METRICS_ACCESS_TOKEN }}
          user_name: IzonIcy
          git_user_name: IzonIcy
          git_user_email: IzonIcy@users.noreply.github.com
          excluded_repos: ${{ secrets.METRICS_EXCLUDED_REPOS }}
          excluded_languages: ${{ secrets.METRICS_EXCLUDED_LANGUAGES }}
